[project]
name = "stacking-as-a-service"
description = "A Clarity smart contract ecosystem for BTC stacking and reward distribution"
authors = []
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.stacking-service]
path = "contracts/stacking-service.clar"
depends_on = []

[contracts.stacking-rewards-pool]
path = "contracts/stacking-rewards-pool.clar"
depends_on = ["stacking-service"]

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = false
